Update README.md
marioquintalcob/Proyecto01Equipo16 pull request #21
Opened 2023-05-22 18:04 UTC by marioquintalcob

Actualización del readme, revisen para ver si falta, sobra o hay que cambiar algo.

2023-05-22 21:46 UTC, n-DiegoTF approved these changes

2023-05-22 23:29 UTC, YaelRmz requested changes

2023-05-22 23:29 UTC, YaelRmz commented on README.md
> +Tambien se implemento el uso de Cardviews, utilizando un adaptador y su recyclerview para su correcto funcionamiento:
Las CardViews se implementaron en el Home y este es el código de Routines

2023-05-22 23:29 UTC, YaelRmz commented on README.md
>  ### Sesión 8
La parte del a session 8 es el buildType que está en el build.gradle a nivel de app

2023-05-23 01:36 UTC, YaelRmz requested changes

2023-05-23 01:36 UTC, YaelRmz commented on README.md
> +Las CardViews se implementaron en el Home:
Este es el NavBar no el archivo Home 😅

2023-05-23 01:41 UTC, YaelRmz approved these changes

2023-05-23 01:41 UTC, merged