D1805
marioquintalcob/Proyecto01Equipo16 pull request #8
Opened 2023-05-18 16:38 UTC by n-DiegoTF

Cambios actualizados

2023-05-18 21:03 UTC, YaelRmz requested changes

2023-05-18 21:03 UTC, YaelRmz commented on app/src/main/java/org/bedu/proyecto01equipo16/MainActivity.kt
> +            val intent = Intent(this, Rutinas::class.java ).apply{
Esto truena, creo que deberías dejarlo como estaba

2023-05-18 21:03 UTC, YaelRmz commented on app/src/main/java/org/bedu/proyecto01equipo16/Rutinas.kt
> +private const val ARG_PARAM1 = "param1"
Deberías borrar todo el código auto generado si no lo estas ocupando (como en este caso)

2023-05-18 21:03 UTC, YaelRmz commented on app/src/main/res/layout/fragment_nutrition.xml
> +    tools:context=".Rutinas">
Deberías cambiar el nombre del XML fragment_nutrition.xml a fragment_rutinas.xml o parecido

2023-05-18 21:03 UTC, YaelRmz commented on app/src/main/java/org/bedu/proyecto01equipo16/Rutinas.kt
> +            R.drawable.a,
Deberías usar nombres de resources más descriptivos para facilidad de entendimiento

2023-05-19 16:39 UTC, n-DiegoTF reviewed
@YaelRmz mira, ya estaba creo.

2023-05-19 20:30 UTC, YaelRmz requested changes

2023-05-19 20:30 UTC, YaelRmz commented on app/src/main/java/org/bedu/proyecto01equipo16/Rutinas.kt
> +private const val ARG_PARAM1 = "param1"
Las variables ARG_PARAM1 2, el companion object los estas utilizando?

2023-05-20 01:04 UTC, merged