Primera versión para el Home
marioquintalcob/Proyecto01Equipo16 pull request #9
Opened 2023-05-18 18:24 UTC by YaelRmz

2023-05-18 21:50 UTC, n-DiegoTF requested changes

2023-05-18 21:50 UTC, n-DiegoTF commented on app/src/main/res/drawable/settings_48.xml
> +<vector android:height="48dp" android:tint="#EB5CFF"
Te dejo el color de los iconos #fda55e

<color name="orange">#fda55e</color>

2023-05-18 21:50 UTC, n-DiegoTF commented on app/src/main/res/layout/fragment_home.xml
> -    android:background="#09a3ad"
Para backgroud podemos utilizar el color #FAFAFA

<color name="orange">#FAFAFA</color>

2023-05-18 21:50 UTC, n-DiegoTF commented on app/src/main/res/layout/fragment_home.xml
> +            app:cardCornerRadius="40dp">
Aqui puede ser:

app:cardCornerRadius="12dp"> ó app:cardCornerRadius="8dp">

2023-05-18 21:50 UTC, n-DiegoTF commented on app/src/main/res/layout/fragment_home.xml
> +                app:cardCornerRadius="20dp">
Igual CornerRadius a las demás tarjetas 12dp o 7 dp

2023-05-18 21:52 UTC, YaelRmz commented on app/src/main/res/drawable/settings_48.xml
> +<vector android:height="48dp" android:tint="#EB5CFF"
Ya hay una variable asignada para ese color? O la genero de una vez?

2023-05-18 21:53 UTC, YaelRmz commented on app/src/main/res/layout/fragment_home.xml
> -    android:background="#09a3ad"
Ya hay alguna variable?

2023-05-18 21:55 UTC, n-DiegoTF commented on app/src/main/res/drawable/settings_48.xml
> +<vector android:height="48dp" android:tint="#EB5CFF"
Si hay una que es @orange pero estaba en mis commits que se aprobaron antier.

2023-05-18 21:55 UTC, n-DiegoTF commented on app/src/main/res/layout/fragment_home.xml
> -    android:background="#09a3ad"
Para este no

2023-05-18 21:57 UTC, YaelRmz commented on app/src/main/res/layout/fragment_home.xml
> +                app:cardCornerRadius="20dp">
Sería bueno seguir la regla de 8, así que 8dp o 16dp?

2023-05-18 22:00 UTC, n-DiegoTF commented on app/src/main/res/layout/fragment_home.xml
> +                app:cardCornerRadius="20dp">
Echale 8. Porfa

2023-05-19 15:18 UTC, YaelRmz commented on app/src/main/res/layout/fragment_home.xml
> -    android:background="#09a3ad"
Oye fue tu comentario fue en una linea de código que no está en mi actual commit, quieres que agregue esa linea con el valor que dices?

2023-05-19 15:41 UTC, n-DiegoTF commented on app/src/main/res/layout/fragment_home.xml
> -    android:background="#09a3ad"
Si no dejemosle background blanco, no la agregues

2023-05-19 16:59 UTC, n-DiegoTF approved these changes

2023-05-19 16:59 UTC, merged